name: Test workflow

on:
  push:
    paths:
    - 'PDF/**'
    branches:
    - main

jobs:
  # This workflow contains a single job called "greet"
  update_wiki:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: Update wiki
    steps:
    - uses: OrlovM/Wiki-Action@v1
      with:
        path: 'wiki'
        token: '${{ secrets.GITHUB_TOKEN }}'
