name: Test workflow

on:
  push:
    paths:
    - 'PDF/**'
    branches:
    - main

jobs:
  # This workflow contains a single job called "greet"
  update_wiki:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: Update wiki
    steps:
    - name: GIT checkout
      uses: actions/checkout@v2
      with:
        path: hellofresh
      
    - name: run smth
      run: |
        cd ./hellofresh
        echo "Currently available" > ./README.md
        echo "" >> ./README.md
        echo "***" >> ./README.md
        echo "" >> ./README.md
        for i in `ls ./PDF`; do (food=`echo ${i} | sed 's/-[0-9a-f-]\{33\}.pdf//g' | sed 's/-/ /g'`;echo "[${food^}](PDF/${i})"; echo ""); done >> ./README.md
        echo "***" >> ./README.md
        echo "" >> ./README.md
        echo "Updated: `date`" >> ./README.md
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
      
#    - uses: OrlovM/Wiki-Action@v1
#      with:
#        path: 'wiki/hellofresh'
#        token: '${{ secrets.GITHUB_TOKEN }}'
