name: Test workflow

on:
  push:
    paths:
    - 'PDF/**'
    branches:
    - main

jobs:
  # This workflow contains a single job called "greet"
  update_wiki:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: Update wiki
    steps:
    - name: GIT checkout
      uses: actions/checkout@v2
      with:
        path: hellofresh
      
    - name: run smth
      run: |
        cd ./hellofresh
        date > ./wiki/updated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./wiki/*
        git commit -m "generated"
        git push
      
    - uses: OrlovM/Wiki-Action@v1
      with:
        path: 'wiki/hellofresh'
        token: '${{ secrets.GITHUB_TOKEN }}'
